### ISSUE TITLE
readme missing wallet address

### ISSUE THREAD

**Issue by lathanbritz** [yyolk/xrpl-price-persist-oracle-sam#24]
no where in the readme do you mention the wallet that is publishing this info, nor where to look for it.

**Comment by yyolk** [comment]
it's in the deployment :) 

it could be literally in the README that's not a problem

![image](https://user-images.githubusercontent.com/134478/129839686-64734cff-86bd-4a04-9838-406e0e7d2ae5.png)
(click view deployment) ![image](https://user-images.githubusercontent.com/134478/129839721-4616d736-9784-4d7d-b78b-1a933ca54995.png)
